import { useMemo } from 'react'
import type { Book } from '../model/book.types'

const SAMPLE_BOOKS: Book[] = [
  {
    id: '1',
    title: 'Le Seigneur des Anneaux',
    author: 'J.R.R. Tolkien',
    authorId: 'jrr-tolkien',
    genre: 'Fantasy',
    language: 'Français',
    publishedDate: '1954',
    coverUrl:
      'https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?w=300&h=450&fit=crop',
    pageCount: 1000,
    rating: 4.9,
    copies: 3,
    summary: 'Un épique voyage pour détruire un anneau magique.',
    seriesId: null,
    seriesTitle: null,
    tomeNumber: null,
    collectionId: null,
    collectionLabel: null,
  },
  {
    id: '2',
    title: 'Fondation',
    author: 'Isaac Asimov',
    authorId: 'isaac-asimov',
    genre: 'Science-Fiction',
    language: 'Français',
    publishedDate: '1951',
    coverUrl:
      'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=300&h=450&fit=crop',
    pageCount: 255,
    rating: 4.7,
    copies: 2,
    summary: 'Un cycle fondamental de la science-fiction.',
    seriesId: null,
    seriesTitle: null,
    tomeNumber: null,
    collectionId: null,
    collectionLabel: null,
  },
  {
    id: '3',
    title: 'Dune',
    author: 'Frank Herbert',
    authorId: 'frank-herbert',
    genre: 'Science-Fiction',
    language: 'Français',
    publishedDate: '1965',
    coverUrl:
      'https://images.unsplash.com/photo-1507842217343-583b8a1a21bc?w=300&h=450&fit=crop',
    pageCount: 680,
    rating: 4.8,
    copies: 2,
    summary: 'Une épopée sur la planète Arrakis.',
    seriesId: null,
    seriesTitle: null,
    tomeNumber: null,
    collectionId: null,
    collectionLabel: null,
  },
  {
    id: '4',
    title: 'Le Hobbit',
    author: 'J.R.R. Tolkien',
    authorId: 'jrr-tolkien',
    genre: 'Fantasy',
    language: 'Français',
    publishedDate: '1937',
    coverUrl:
      'https://images.unsplash.com/photo-1526243741027-444220a728bb?w=300&h=450&fit=crop',
    pageCount: 310,
    rating: 4.8,
    copies: 4,
    summary: "L'aventure de Bilbo Sacquet.",
    seriesId: null,
    seriesTitle: null,
    tomeNumber: null,
    collectionId: null,
    collectionLabel: null,
  },
  {
    id: '5',
    title: 'Neuromancien',
    author: 'William Gibson',
    authorId: 'william-gibson',
    genre: 'Science-Fiction',
    language: 'Français',
    publishedDate: '1984',
    coverUrl:
      'https://images.unsplash.com/photo-1533212467805-e5f3d5373cf5?w=300&h=450&fit=crop',
    pageCount: 271,
    rating: 4.6,
    copies: 1,
    summary: 'Un classique du cyberpunk.',
    seriesId: null,
    seriesTitle: null,
    tomeNumber: null,
    collectionId: null,
    collectionLabel: null,
  },
  {
    id: '6',
    title: 'Le Nom du Vent',
    author: 'Patrick Rothfuss',
    authorId: 'patrick-rothfuss',
    genre: 'Fantasy',
    language: 'Français',
    publishedDate: '2007',
    coverUrl:
      'https://images.unsplash.com/photo-1543002588-d83cea6d0b06?w=300&h=450&fit=crop',
    pageCount: 662,
    rating: 4.7,
    copies: 3,
    summary: 'Les chroniques de Kvothe, un magicien légendaire.',
    seriesId: null,
    seriesTitle: null,
    tomeNumber: null,
    collectionId: null,
    collectionLabel: null,
  },
]

export function useSampleBooks(): Book[] {
  return useMemo(() => SAMPLE_BOOKS, [])
}
